version: "3"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app/backend
  frontend:
    stdin_open: true
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app/frontend
    depends_on:
      - backend
