version: "3"
services:
  backend:
    image: michalzdev/kanbak_production_backend:latest
    ports:
      - "5000:5000"
    container_name: kanbak_production_backend
  frontend:
    stdin_open: true
    image: michalzdev/kanbak_production_frontend:latest
    ports:
      - "3000:3000"
    container_name: kanbak_production_frontend
    depends_on:
      - backend
